import Header from '@/components/section/Header'
import Head from 'next/head'
import React, { ReactNode } from 'react'

export interface IPrimarylayout {
  children: ReactNode
  pageTitle: string
}

const PrimaryLayout = ({ children, pageTitle }: IPrimarylayout) => {
  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header/>
      <main>{children}</main>
    </>
  )
}

export default PrimaryLayout
